CREATE TABLE IF NOT EXISTS payment (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    title TEXT NOT NULL,
    value INTEGER NOT NULL,
    amount INTEGER NOT NULL DEFAULT 1,
    date_p TIMESTAMP NOT NULL
)
